load debug.maude
load as4cpx.maude

fmod DIRAC is
    pr CPX .
    ---
    sorts BKet Ket BBra Bra BBraKet BraKet .
    subsort BKet < Ket .
    subsort BBra < Bra .
    subsort BBraKet < BraKet .
    --- basis vectors
    ops |0> |1> : -> BKet [ctor] .
    --- basis covectors
    ops <0| <1| : -> BBra [ctor] .
    --- basis matries
    ops |0><0| |0><1| |1><0| |1><1| : -> BBraKet [ctor] .
endfm

fmod MAT is
    pr CPX .
    pr DIRAC .

    sorts ZeroV Vect ZeroCV CoVect ZeroM Mat .
    subsorts ZeroV Ket < Vect .
    subsorts ZeroM BraKet < Mat .
    subsorts ZeroCV Bra < CoVect .

    --- zero vector, covector and matrix
    op O   : -> ZeroV [ctor] .
    op O^+ : -> ZeroCV [ctor] .
    op mO  : -> ZeroM [ctor] .
    --- identity matrix
    op I : -> Mat [ctor] .
    --- scalar multiplication with matrix
    op _._ : Cpx Ket -> Ket [prec 31] .
    op _._ : Cpx Bra -> Bra [prec 31] .
    op _._ : Cpx BraKet -> BraKet [prec 31] .
    op _._ : Cpx Vect -> Vect [prec 31] .
    op _._ : Cpx CoVect -> CoVect [prec 31] .
    op _._ : Cpx Mat -> Mat [prec 31] .
    --- matrix addition
    op _+_ : Ket Ket -> Ket [comm assoc prec 34] .
    op _+_ : Bra Bra -> Bra [comm assoc prec 34] .
    op _+_ : BraKet BraKet -> BraKet [comm assoc prec 34] .
    op _+_ : Vect Vect -> Vect [comm assoc prec 34] .
    op _+_ : CoVect CoVect -> CoVect [comm assoc prec 34] .
    op _+_ : Mat Mat -> Mat [comm assoc prec 34] .
    --- matrix product
    op _x_ : Ket Bra -> BraKet [prec 32] .
    op _x_ : Mat Vect -> Vect [prec 32] .
    op _x_ : Vect CoVect -> Mat [prec 32] .
    op _x_ : Mat Mat -> Mat [assoc prec 33] .
    --- tensor product
    op _(x)_ : Vect Vect -> Vect [assoc prec 30] .
    op _(x)_ : CoVect CoVect -> CoVect [assoc prec 30] .
    op _(x)_ : Mat Mat -> Mat [assoc prec 30] .
    --- dagger
    op (_)^+ : Vect -> CoVect [prec 29] .
    op (_)^+ : CoVect -> Vect [prec 29] .
    op (_)^+ : Mat -> Mat [prec 29] .
    --- inner product
    op <_,_> : Vect Vect -> Cpx .
    --- norm square
    op ||_||^2 : Vect -> Cpx .

    vars M M1 M2 M3 M4 : Mat .
    vars V V1 V2 V3 V4 : Vect .
    vars CV CV1 CV2 CV3 : CoVect .
    vars C C1 C2 : NzCpx .
    vars K K1 K2 : BKet .
    vars B B1 B2 : BBra .
    vars BK : BraKet .

    --- abbreviations for basic matrices
    eq |0><0| = |0> x <0| .
    eq |0><1| = |0> x <1| .
    eq |1><0| = |1> x <0| .
    eq |1><1| = |1> x <1| .

    --- @todo: norm square
    eq || V ||^2 = < V, V > .

    --- inner product
    eq < V, O > = (0,0,0,0) .
    eq < O, V > = (0,0,0,0) .
    eq < K1, K2 > = if K1 == K2 then (1,0,0,0) else (0,0,0,0) fi .
    eq < C1 . V1, V2 > = (C1)^* * < V1, V2 > .
    eq < V1, C2 . V2 > = C2 * < V1, V2 > .
    eq < V1 + V2, V3 > = < V1, V3 > + < V2, V3 > .
    eq < V1, V2 + V3 > = < V1, V2 > + < V1, V3 > .
    eq < K1 (x) V1, K2 (x) V2 > = if K1 == K2 then < V1, V2 > else (0,0,0,0) fi . --- optimize
    eq (< V1, V2 >)^* = < V2, V1 > .

    --- zero vector
    eq [scalar-O1] : (0,0,0,0) . V = O .
    eq [scalar-O2] : C . O = O .
    eq [add-O1] : O + V = V .
    eq [mul-O1] : M x O = O .
    eq [mul-O2] : mO x V = O .
    eq [tensor-O1] : V (x) O = O .
    eq [tensor-O2] : O (x) V = O .

    --- zero covector
    eq [d-scalar-O1] : (0,0,0,0) . CV = O^+ .
    eq [d-scalar-O2] : C . O^+ = O^+ .
    eq [d-add-O1] : O^+ + CV = CV .
    eq [d-mul-O1] : V x O^+ = mO .
    eq [d-mul-O2] : O x CV = mO .
    eq [d-tensor-O1] : CV (x) O^+ = O^+ .
    eq [d-tensor-O2] : O^+ (x) CV = O^+ .

    --- zero matrix
    eq [m-scalar-O1] : (0,0,0,0) . M = mO .
    eq [m-scalar-O2] : C . mO = mO .
    eq [m-add-O1] : M + mO = M .
    eq [m-mul-O1] : M x mO = mO .
    eq [m-mul-O2] : mO x M = mO .
    eq [m-tensor-O1] : mO (x) M = mO .
    eq [m-tensor-O2] : M (x) mO = mO .

    --- identity matrix properties
    eq [mul-I1] : I x M = M .
    eq [mul-I2] : M x I = M .
    eq [mul-I3] : I x V = V .
    ---
    --- dagger properties
    eq [dagger-V1] : (O)^+ = O^+ .
    eq [dagger-V2] : (|0>)^+ = <0| .
    eq [dagger-V3] : (|1>)^+ = <1| .
    eq [dagger-V4] : (C . V)^+ = ((C)^*) . (V)^+ .
    eq [dagger-V5] : (V1 + V2)^+ = (V1)^+ + (V2)^+ .
    eq [dagger-V6] : (V1 (x) V2)^+ = (V1)^+ (x) (V2)^+ .
    eq [dagger-V7] : ((V)^+)^+ = V .
    ---
    eq [dagger-CV1] : (O^+)^+ = O .
    eq [dagger-CV2] : (<0|)^+ = |0> .
    eq [dagger-CV3] : (<1|)^+ = |1> .
    eq [dagger-CV4] : (C . CV)^+ = ((C)^*) . (CV)^+ .
    eq [dagger-CV5] : (CV1 + CV2)^+ = (CV1)^+ + (CV2)^+ .
    eq [dagger-CV6] : (CV1 (x) CV2)^+ = (CV1)^+ (x) (CV2)^+ .
    eq [dagger-CV7] : ((CV)^+)^+ = CV .
    --- 
    eq [dagger-M1] : (mO)^+ = mO .
    eq [dagger-M2] : (I)^+ = I .
    eq [dagger-M3] : (K x B)^+ =  (B)^+ x (K)^+ .
    eq [dagger-M4] : (C . M)^+ = ((C)^*) . (M)^+ .
    eq [dagger-M5] : (M1 + M2)^+ = (M1)^+ + (M2)^+ .
    eq [dagger-M6] : (M1 x M2)^+ = (M2)^+ x (M1)^+ .
    eq [dagger-M7] : (M1 (x) M2)^+ = (M1)^+ (x) (M2)^+ .
    eq [dagger-M8] : ((M)^+)^+ = M .

    --- scalar normal forms
    eq [scalar-V1] : (1,0,0,0) . V = V .
    eq [scalar-V2] : C1 . (C2 . V) = (C1 * C2) . V .
    eq [scalar-V3] : C . (V1 + V2) = C . V1 + C . V2 .
    ---
    eq [scalar-CV1] : (1,0,0,0) . CV = CV .
    eq [scalar-CV2] : C1 . (C2 . CV) = (C1 * C2) . CV .
    eq [scalar-CV3] : C . (CV1 + CV2) = C . CV1 + C . CV2 .
    ---
    eq [scalar-M1] : (1,0,0,0) . M = M .
    eq [scalar-M2] : C1 . (C2 . M) = (C1 * C2) . M .
    eq [scalar-M3] : C . (M1 + M2) = C . M1 + C . M2 .

    --- additive normal forms
    eq [add-V1] : V + V = (2,0,0,0) . V .
    eq [add-V2] : (C . V) + V = (C + (1,0,0,0)) . V .
    eq [add-V3] : (C1 . V) + (C2 . V) = (C1 + C2) . V .
    
    eq [add-CV1] : CV + CV = (2,0,0,0) . CV .
    eq [add-CV2] : (C . CV) + CV = (C + (1,0,0,0)) . CV .
    eq [add-CV3] : (C1 . CV) + (C2 . CV) = (C1 + C2) . CV .

    eq [add-M1] : M + M = (2,0,0,0) . M .
    eq [add-M2] : (C . M) + M = (C + (1,0,0,0)) . M .
    eq [add-M3] : (C1 . M) + (C2 . M) = (C1 + C2) . M .
    
    --- tensor product normal forms
    eq [tensor-V2] : C . (V1 (x) V2) = V1 (x) (C . V2) .
    eq [tensor-V3] : (C . V1) (x) V2 = V1 (x) (C . V2) .
    eq [tensor-V4] : K1 (x) V1 + K1 (x) V2 = K1 (x) (V1 + V2) .
    ---
    eq [tensor-CV2] : C . (CV1 (x) CV2) = CV1 (x) (C . CV2) .
    eq [tensor-CV3] : (C . CV1) (x) CV2 = CV1 (x) (C . CV2) .
    eq [tensor-CV4] : B1 (x) CV1 + B1 (x) CV2 = B1 (x) (CV1 + CV2) .
    ---
    eq [tensor-M1] : (C . M1) (x) M2 = C . (M1 (x) M2) .
    eq [tensor-M2] : M1 (x) (C . M2) = C . (M1 (x) M2) .

    --- tensor distributes over addition
    eq [dist-tensor-V1] : (V1 + V2) (x) V3 = V1 (x) V3 + V2 (x) V3 .
    ---
    eq [dist-tensor-CV1] : (CV1 + CV2) (x) CV3 = CV1 (x) CV3 + CV2 (x) CV3 .

    --- multiplicative normal forms
    eq [mul-MV1] : (C . M) x V = C . (M x V) .
    eq [mul-MV2] : M x (C . V) = C . (M x V) .
    ---
    eq [mul-VCV1] : (C . V) x CV = C . (V x CV) .
    eq [mul-VCV2] : V x (C . CV) = C . (V x CV) .  
    ---
    eq [mul-MM1] : (C . M1) x M2 = C . (M1 x M2) .
    eq [mul-MM2] : M1 x (C . M2) = C . (M1 x M2) .

    --- multiplication distributes over addition
    eq [dist-mul-V1] : M x (|0> (x) V1 + |1> (x) V2) = M x (|0> (x) V1) + M x (|1> (x) V2) .
    eq [dist-mul-V2] : M x (C1 . |0> + C2 . |1>) = M x (C1 . |0>) + M x (C2 . |1>) .
    eq [dist-mul-V3] : M x (C1 . |0> + |1>) = M x (C1 . |0>) + M x |1> .
    eq [dist-mul-V4] : M x (|0> + C2 . |1>) = M x |0> + M x (C2 . |1>) .
    eq [dist-mul-V5] : M x (|0> + |1>) = M x |0> + M x |1> .
    eq [dist-mul-V6] : (M1 + M2) x V = M1 x V + M2 x V .
    ---
    eq [dist-mul-CV1] : V x (CV1 + CV2) = V x CV1 + V x CV2 .
    eq [dist-mul-CV2] : (V1 + V2) x CV = V1 x CV + V2 x CV .
    ---
    eq [dist-mul-M1] : M1 x (M2 + M3) = M1 x M2 + M1 x M3 .
    eq [dist-mul-M2] : (M1 + M2) x M3 = M1 x M3 + M2 x M3 .

    --- multiplication with tensor product
    ceq [mul-MV3] : (BK (x) M2) x (K2 (x) V2) = (if V1 == O then O else V1 (x) (M2 x V2) fi) if V1 := BK x K2 . --- optimize
    eq  [mul-MV4] : (I (x) M2) x (K2 (x) V2) = K2 (x) (M2 x V2) .
    ceq [mul-MV5] : (K1 x B1) x K2 = V if V := < (B1)^+, K2 > . K1 . --- optimize
    ceq [mul-MV6] : (M1 x M2) x V = M1 x V1 if V1 := (M2 x V) [print "M2 = " M2 ", M1 = " M1] .
    ---
    eq [mul-VCV3] : (K (x) V) x (B (x) CV) = (K x B) (x) (V x CV) .
    ---
    eq [mul-MM1] : (C . M1) x M2 = C . (M1 x M2) .
    --- eq [mul-MM2] : (I (x) M1) x (I (x) M2) = I (x) (M1 x M2) .
endfm

fmod QC is
    pr MAT .
    pr NAT-LIST .

    sorts ErrNat Nat&Err .
    subsort Nat ErrNat < Nat&Err .

    op I : Nat -> Mat .
    op size : Vect -> Nat .
    op size : Mat  -> Nat .
    op errNat : -> ErrNat [ctor] .

    vars N N1 N2 N3 : Nat .
    vars V V1 V2 : Vect .
    vars M M1 M2 : Mat .
    vars K K1 K2 : Ket .
    vars B : Bra .
    vars C : Cpx .
    vars NL : NatList .

    eq  [I1] : I(0) (x) M = M .
    eq  [I2] : M (x) I(0) = M .
    ceq [I3] : I(N) = I (x) I(sd(N,1)) if N > 0 .

    eq  [size1.1]  : size(K) = 1 .
    eq  [size1.2]  : size(C . V) = size(V) .
    ceq [size1.3]  : size(V1 + V2) = size(V1) if size(V1) == size(V2) .
    ceq [size1.3E] : size(V1 + V2) = errNat if size(V1) =/= size(V2) .
    ceq [size1.4]  : size(M x V) = size(V) if size(M) == size(V) .
    ceq [size1.4E] : size(M x V) = errNat if size(M) =/= size(V) .
    eq  [size1.5]  : size(V1 (x) V2) = size(V1) + size(V2) .

    eq  [size2.1]  : size(K x B) = 1 .
    eq  [size2.2]  : size(C . M) = size(M) .
    ceq [size2.3]  : size(M1 + M2) = size(M1) if size(M1) == size(M2) .
    ceq [size2.3E] : size(M1 + M2) = errNat if size(M1) =/= size(M2) .
    ceq [size2.4]  : size(M1 x M2) = size(M1) if size(M1) == size(M2) .
    ceq [size2.4E] : size(M1 x M2) = errNat if size(M1) =/= size(M2) .
    eq  [size2.5]  : size(M1 (x) M2) = size(M1) + size(M2) .

    --- quantum gates
    ops P0 P1 I X Y Z H S T Rx Ry : Nat -> Mat .
    ops CX CY CZ SWAP : Nat Nat -> Mat .
    ops CCX CCZ CSWAP : Nat Nat Nat -> Mat .
    ops MCX MCZ : NatList Nat -> Mat .
    op  MCSWAP : NatList Nat Nat -> Mat .
    --- 
    op sizeV : -> Nat .

    --- single-qubit gates
    eq [P0] : P0(N) x V = (I(N) (x) |0><0| (x) I(sd(sizeV, N + 1))) x V .
    eq [P1] : P1(N) x V = (I(N) (x) |1><1| (x) I(sd(sizeV, N + 1))) x V .
    eq [I]  : I(N) x V  = V .
    
    eq [X]  : X(N) x V  = (I(N) (x) (|0><1| + |1><0|) (x) I(sd(sizeV, N + 1))) x V .
    eq [Y]  : Y(N) x V  = (I(N) (x) ((0,0,-1,0) . |0><1| + (0,0,1,0) . |1><0|) (x) I(sd(sizeV, N + 1))) x V .
    eq [Z]  : Z(N) x V  = (I(N) (x) (|0><0| + (-1,0,0,0) . |1><1|) (x) I(sd(sizeV, N + 1))) x V .
    --- H: ignore 1/sqrt(2) factor
    eq [H]  : H(N) x V  = (I(N) (x) (|0><0| + |0><1| + |1><0| + (-1,0,0,0) . |1><1|) (x) I(sd(sizeV, N + 1))) x V .
    eq [S]  : S(N) x V  = (P0(N) + ((0,0,1,0) . P1(N))) x V .
    eq [T]  : T(N) x V  = (P0(N) + (0,1,0,0) . P1(N)) x V .
    --- Rx[pi/2]: ignore 1/sqrt(2) factor
    eq [Rx]  : Rx(N) x V  = (I(N) (x) (|0><0| + (0,0,-1,0) . |0><1| + (0,0,-1,0) . |1><0| + |1><1|) (x) I(sd(sizeV, N + 1))) x V .
    --- Ry[pi/2]: ignore 1/sqrt(2) factor
    eq [Ry]  : Ry(N) x V  = (I(N) (x) (|0><0| + (-1,0,0,0) . |0><1| + |1><0| + |1><1|) (x) I(sd(sizeV, N + 1))) x V .

    --- two-qubit gates
    eq [CX]    : CX(N1, N2) x V   = (P0(N1) + (X(N2) x P1(N1))) x V .
    eq [CY]    : CY(N1, N2) x V   = (P0(N1) + (Y(N2) x P1(N1))) x V .
    eq [CZ]    : CZ(N1, N2) x V   = (P0(N1) + (Z(N2) x P1(N1))) x V .
    eq [SWAP]  : SWAP(N1, N2) x V = (CX(N1, N2) x CX(N2, N1) x CX(N1, N2)) x V .

    --- three-qubit gates
    eq [CCX]   : CCX(N1, N2, N3) x V   = (P0(N1) + (CX(N2, N3) x P1(N1))) x V .
    eq [CCZ]   : CCZ(N1, N2, N3) x V   = (P0(N1) + (CZ(N2, N3) x P1(N1))) x V .
    eq [CSWAP] : CSWAP(N1, N2, N3) x V = (P0(N1) + (SWAP(N2,N3) x P1(N1))) x V .

    --- multiple qubit gates
    eq [MCX] : MCX(N1 NL, N) x V = (P0(N1) + (MCX(NL, N) x P1(N1))) x V .
    eq [MCX] : MCX(nil, N) x V = X(N) x V .
    eq [MCZ] : MCZ(N1 NL, N) x V = (P0(N1) + (MCZ(NL, N) x P1(N1))) x V .
    eq [MCZ] : MCZ(nil, N) x V = Z(N) x V .
    eq [MCSWAP] : MCSWAP(N1 NL, N2, N3) x V = (P0(N1) + (MCSWAP(NL, N2, N3) x P1(N1))) x V .
    eq [MCSWAP] : MCSWAP(nil, N2, N3) x V = SWAP(N2,N3) x V .
endfm

fmod TEST is
    pr QC .
    --- @todo: MUST set the size of V in advance
    eq sizeV = 3 .
endfm

red (H(2) x H(1) x H(0)) x (|0> (x) |0> (x) |0> + |0> (x) |0> (x) |1>) .

eof

red H(0) x (|0> (x) |0> (x) |0>) .
red H(2) x H(1) x H(0) x (|0> (x) |0> (x) |0>) .
red H(0) x (|0> (x) |0> (x) (|0> + |1>)) .
red H(0) x (|0> (x) |0> (x) ((2,0,0,0) . |0> + |1>)) .
red H(0) x (|0> (x) |0> (x) (|0> + (2,0,0,0) . |1>)) .
red H(0) x (|0> (x) |0> (x) ((2,0,0,0) . |0> + (2,0,0,0) . |1>)) .

eof

red (|0> (x) |0> +  |0> (x) |0>) (x) |0> .
red (|0> (x) |0> +  |1> (x) |1>) (x) |0> .
red |0> (x) (|0> (x) |0> + |0> (x) |1> + |1> (x) |0> + |1> (x) |1>) .

eof

red |0> (x) (|0> + |1>) (x) |0> + |0> (x) (|0> + |1>) (x) |1> .
red H(0) x ((2,0,0,0) . |0> (x) |0> (x) |0> + (2,0,0,0) . |1> (x) |0> (x) |1>) .

eof 

red H(0) x ((2,0,0,0) . |0> (x) |0> (x) |0> + (2,0,0,0) . |0> (x) |0> (x) |1>) .

red H(0) x ((2,0,0,0) . |0> (x) |0> (x) |0> + 
    (2,0,0,0) . |0> (x) |0> (x) |1>) .

eof