in debug.maude

fmod FLOAT-RENAME is
    pr FLOAT * (
        op -_ : Float -> Float to -f_,
        op _+_ : Float Float -> Float to _+f_,
        op _-_ : Float Float -> Float to _-f_,
        op _*_ : Float Float -> Float to _*f_,
        op _/_ : [Float] [Float] -> [Float] to _/f_,
        op _rem_ : [Float] [Float] -> [Float] to _remf_,
        op _^_ : [Float] [Float] -> [Float] to _^f_,
        op abs : Float -> Float to absf,
        op sqrt : [Float] -> [Float] to sqrtf,
        op floor : Float -> Float to floorf,
        op ceiling : Float -> Float to ceilingf,
        op min : Float Float -> Float to minf,
        op max : Float Float -> Float to maxf,
        op _<_ : Float Float -> Bool to _<f_,
        op _>_ : Float Float -> Bool to _>f_,
        op _<=_ : Float Float -> Bool to _<=f_,
        op _>=_ : Float Float -> Bool to _>=f_
    ) .
    sort ZeroF .
    subsort ZeroF < FiniteFloat .
    mb (0.) : ZeroF .

    sorts ErrFloat Float&Err .
    subsorts ErrFloat Float < Float&Err .
    op errF : -> ErrFloat [ctor] .
endfm

fmod CONVERSION-RENAME is
    pr RAT .
    pr FLOAT-RENAME .
    pr STRING .
    sort DecFloat .
    op <_,_,_> : Int String Int -> DecFloat [ctor] .
    op float : Rat -> Float [special (
        id-hook FloatOpSymbol (float)
        op-hook floatSymbol (<Floats> : ~> Float)
        op-hook succSymbol (s_ : Nat ~> NzNat)
        op-hook minusSymbol (-_ : NzNat ~> Int)
        op-hook divisionSymbol (_/_ : NzInt NzNat ~> NzRat))] .
    op rat : FiniteFloat -> Rat [special (
        id-hook FloatOpSymbol (rat)
        op-hook floatSymbol (<Floats> : ~> Float)
        op-hook succSymbol (s_ : Nat ~> NzNat)
        op-hook minusSymbol (-_ : NzNat ~> Int)
        op-hook divisionSymbol (_/_ : NzInt NzNat ~> NzRat))] .
    op string : [Rat] [NzNat] -> [String] [special (
        id-hook StringOpSymbol (string)
        op-hook stringSymbol (<Strings> : ~> String)
        op-hook succSymbol (s_ : Nat ~> NzNat)
        op-hook minusSymbol (-_ : NzNat ~> Int)
        op-hook divisionSymbol (_/_ : NzInt NzNat ~> NzRat))] .
    op rat : [String] [NzNat] -> [Rat] [special (
        id-hook StringOpSymbol (rat)
        op-hook stringSymbol (<Strings> : ~> String)
        op-hook succSymbol (s_ : Nat ~> NzNat)
        op-hook minusSymbol (-_ : NzNat ~> Int)
        op-hook divisionSymbol (_/_ : NzInt NzNat ~> NzRat))] .
    op string : Float -> String [special (
        id-hook StringOpSymbol (string)
        op-hook stringSymbol (<Strings> : ~> String)
        op-hook floatSymbol (<Floats> : ~> Float))] .
    op float : [String] -> [Float] [special (
        id-hook StringOpSymbol (float)
        op-hook stringSymbol (<Strings> : ~> String)
        op-hook floatSymbol (<Floats> : ~> Float))] .
    op decFloat : Float Nat -> DecFloat [special (
        id-hook StringOpSymbol (decFloat)
        op-hook stringSymbol (<Strings> : ~> String)
        op-hook floatSymbol (<Floats> : ~> Float)
        op-hook succSymbol (s_ : Nat ~> NzNat)
        op-hook minusSymbol (-_ : NzNat ~> Int)
        op-hook decFloatSymbol (<_, _, _> : Int String Int ~> DecFloat))] .
endfm

fmod CPX-STANDARD is
    pr CONVERSION-RENAME .
    sorts Imag CpxS .
    subsorts Float Imag < CpxS .
    
    op _i : Float -> Imag .
    op _+_ : Float Imag -> CpxS [ctor comm assoc] .
    op _+_ : CpxS CpxS -> CpxS [ditto] .
    op |_| : CpxS -> Float .

    vars F F1 F2 F3 F4 : Float .
    vars I I1 I2 : Imag .
    vars C : CpxS .

    eq 0.0 i = 0.0 .
    eq C + 0.0 = C .
    eq (F1 + F2 i) + (F3 + F4 i) = (F1 +f F3) + (F2 +f F4) i .
    eq (F2 i) + (F3 + F4 i) = F3 + (F2 +f F4) i .
    eq F1 + (F3 + F4 i) = (F1 +f F3) + F4 i .
    eq (F2 i) + (F4 i) = (F2 +f F4) i .
    eq F1 + F3 = F1 +f F3 .
    eq | F1 + F2 i | = sqrtf((F1 *f F1) +f (F2 *f F2)) .
    eq | F1 | = absf(F1) .
    eq | F2 i | = absf(F2) .
endfm

fmod CPX is
    pr CPX-STANDARD .
    sorts ZeroCpx NzCpx Cpx ErrCpx Cpx&Err .
    subsorts ZeroCpx NzCpx < Cpx .
    subsorts Cpx ErrCpx < Cpx&Err .
    op errCpx : -> ErrCpx [ctor] .
    op toCpxS : Cpx -> CpxS .
    op toFloat : Cpx -> Float&Err .
    op (_,_,_,_) : Zero Zero Zero Zero -> ZeroCpx [ctor] .
    op (_,_,_,_) : NzInt Int Int Int -> NzCpx [ctor] .
    op (_,_,_,_) : Int NzInt Int Int -> NzCpx [ctor] .
    op (_,_,_,_) : Int Int NzInt Int -> NzCpx [ctor] .
    op (_,_,_,_) : Int Int Int NzInt -> NzCpx [ctor] .
    op (_,_,_,_) : Int Int Int Int -> Cpx [ctor] .
    op _+_ : Cpx Cpx -> Cpx [comm assoc prec 33] .
    op _*_ : Cpx Cpx -> Cpx [comm assoc prec 31] .
    op _*_ : NzCpx NzCpx -> NzCpx [ditto] .
    op _^* : Cpx -> Cpx [prec 29] .
    op _^* : NzCpx -> NzCpx [prec 29] .
    op calProb : Cpx Nat -> Float .
    op calProb* : Cpx Nat -> Float .

    vars C C1 C2 C3 : NzCpx .
    vars I I1 I2 I3 I4 : Int .
    vars I' I1' I2' I3' I4' : Int .
    vars N N' : Nat .
    vars R1 R2 R3 R4 : Rat .
    
    eq (I1, I2, I3, I4) + (I1', I2', I3', I4') = (I1 + I1', I2 + I2', I3 + I3', I4 + I4') .
    eq (I1, I2, I3, I4) * (I1', I2', I3', I4') 
    = ((I1 * I1') + (- I2 * I4') + (- I3 * I3') + (- I4 * I2'),
        (I1 * I2') + (I2 * I1') + (- I3 * I4') + (- I4 * I3'),
        (I1 * I3') + (I2 * I2') + (I3 * I1') + (- I4 * I4'),
        (I1 * I4') + (I2 * I3') + (I3 * I2') + (I4 * I1') 
        ) .
    eq (I1, I2, I3, I4)^* = (I1, - I4, - I3, - I2) .
    ---
    eq toFloat((I1, 0, 0, 0)) = float(I1) .
    ceq toFloat((I1, I2, 0, I4)) = float(I1) +f (sqrtf(2.0) *f float(I2)) if I2 == - I4 .
    eq toFloat((I1, I2, I3, I4)) = errF [owise] .
    eq toCpxS((I1, I2, I3, I4)) = (float(I1) +f ((float(I2) /f sqrtf(2.0)) -f (float(I4) /f sqrtf(2.0)))) +
                                  (((float(I2) /f sqrtf(2.0)) +f float(I3)) +f (float(I4) /f sqrtf(2.0))) i .
    --- calculate probability
    --- C in C.V
    eq calProb((I1, 0, 0, 0), N) = float(I1 * (I1 / (2 ^ N))) .
    ceq calProb((I1, I2, I3, I4), N) = 
        float(I1 * R1 + I2 * R2 + I3 * R3 + I4 * R4) +f 
        (sqrtf(2.0) *f float(((R1 * (I2 - I4)) + (R2 * I3) + (R3 * I4))))
    if N' := 2 ^ N
    /\ R1 := I1 / N'
    /\ R2 := I2 / N'
    /\ R3 := I3 / N'
    /\ R4 := I4 / N' [owise] .
    --- |C|^2 in C.V
    eq calProb*((I1, 0, 0, 0), N) = float(I1 / (2 ^ N)) .
    ceq calProb*((I1, I2, 0, I4), N) = float(I1 / N') +f (sqrtf(2.0) *f float(I2 / N')) 
    if I2 == - I4 /\ N' := 2 ^ N .
    eq calProb*((I1, I2, I3, I4), N) = errF [owise] .
    --- symbolic reasoning for integers
    eq I * 0 = 0 .
    eq I + 0 = I .
    eq I * 1 = I .
    eq I - I = 0 .
    --- symbolic reasoning for complex numbers
    eq C * (0,0,0,0) = (0,0,0,0) .
    eq C + (0,0,0,0) = C .
    eq C * (1,0,0,0) = C .
    eq (C1 + C2)^* = (C1)^* + (C2)^* .
    eq (C1 * C2)^* = (C1)^* * (C2)^* .
    ceq C1 * C2 * (C2)^* + C1 * C3 * (C3)^* = C1 if C2 * (C2)^* + C3 * (C3)^* == (1,0,0,0) .
endfm