in as4qc.maude

fmod TEST is
    pr QC .
    ops a b : -> NzCpx .
    op |psi> : -> Vect .
    eq |psi> = (a . |0> + b . |1>) .
    --- eq |psi> = a . |0> .
    --- eq |psi> = b . |1> .
endfm

red [H(1) CX(1,2) CX(0, 1) H(0) P0(0) P0(1), ((2,3,4,5) . |0> + (3,4,5,6) . |1>) (x) |0> (x) |0>] .
red [H(1) CX(1,2) CX(0, 1) H(0) P0(0) P0(1), |psi> (x) |0> (x) |0>] .
red [H(1) CX(1,2) CX(0, 1) H(0) P1(0) P0(1) Z(2), |psi> (x) |0> (x) |0>] .
red [H(1) CX(1,2) CX(0, 1) H(0) P0(0) P1(1) X(2), |psi> (x) |0> (x) |0>] .
red [H(1) CX(1,2) CX(0, 1) H(0) P1(0) P1(1) X(2) Z(2), |psi> (x) |0> (x) |0>] .