in ../as4qc.maude

fmod NETWORK-CODING is
    pr QC .
    
    op con(_,(_ |-> _)) : Nat Nat Nat -> GateList .
    op fanout(_,(_ |-> _),(_ |-> _)) : Nat Nat Nat Nat Nat -> GateList .
    op add(_,_,(_ |-> _)) : Nat Nat Nat Nat -> GateList .
    op rem(_ |-> _) : Nat Nat -> GateList .
    op remadd(_ |-> (_,_)) : Nat Nat Nat -> GateList .
    op network-coding : -> GateList .

    vars N N1 N2 N3 N4 N5 : Nat .
    var NzN : NzNat .

    eq con(N1, (N2 |-> N3)) = CX(N1, N2) (P0(N2) U (P1(N2) X(N3))) .
    eq fanout(N1, (N2 |-> N3), (N4 |-> N5)) = con(N1, (N2 |-> N3)) con(N1, (N4 |-> N5)) .
    eq add(N1, N2, (N3 |-> N4)) = CX(N1, N3) CX(N2, N3) (P0(N3) U (P1(N3) X(N4))) .
    eq rem(N1 |-> N2) = H(N1) (P0(N1) U (P1(N1) Z(N2))) .
    eq remadd(N3 |-> (N1, N2)) = H(N3) (P0(N3) U (P1(N3) Z(N1) Z(N2))) .
    eq network-coding = con(0, (2 |-> 3)) con(4, (6 |-> 7)) add(3, 7, (8 |-> 9))
                        fanout(9, (10 |-> 11), (12 |-> 13)) CX(13, 5) CX(11, 1)
                        rem(11 |-> 9) rem(13 |-> 9) remadd(9 |-> (3, 7))
                        rem(3 |-> 0) rem(7 |-> 4) .
    
    op init : Nat -> Vect .
    eq init(0) = |0> .
    eq init(NzN) = |0> (x) init(sd(NzN,1)) .

    op EPR : -> Vect .
    eq EPR = |0> (x) |0> + |1> (x) |1> .
endfm

red check([
    H(0) CX(0,1) H(2) CX(2,3)
    H(4) CX(4,5) H(6) CX(6,7)
    H(8) CX(8,9) H(10) CX(10,11)
    H(12) CX(12,13) network-coding,
    init(13)
], P(0,5,EPR) and P(1,4,EPR)) .