in ../as4qc.maude

fmod NETWORK-CODING is
    pr QC .
    
    op con(_,(_ |-> _)) : Nat Nat Nat -> GateList .
    op fanout(_,(_ |-> _),(_ |-> _)) : Nat Nat Nat Nat Nat -> GateList .
    op add(_,_,(_ |-> _)) : Nat Nat Nat Nat -> GateList .
    op rem(_ |-> _) : Nat Nat -> GateList .
    op remadd(_ |-> (_,_)) : Nat Nat Nat -> GateList .
    op network-coding : -> GateList .

    vars N N1 N2 N3 N4 N5 : Nat .
    var NzN : NzNat .

    eq con(N1, (N2 |-> N3)) = CX(N1, N2) (P0(N2) U (P1(N2) X(N3))) .
    eq fanout(N1, (N2 |-> N3), (N4 |-> N5)) = con(N1, (N2 |-> N3)) con(N1, (N4 |-> N5)) .
    eq add(N1, N2, (N3 |-> N4)) = CX(N1, N3) CX(N2, N3) (P0(N3) U (P1(N3) X(N4))) .
    eq rem(N1 |-> N2) = H(N1) (P0(N1) U (P1(N1) Z(N2))) .
    eq remadd(N3 |-> (N1, N2)) = H(N3) (P0(N3) U (P1(N3) Z(N1) Z(N2))) .
    eq network-coding = con(0, (2 |-> 3)) con(4, (6 |-> 7)) add(3, 7, (8 |-> 9))
                        fanout(9, (10 |-> 11), (12 |-> 13)) CX(13, 5) CX(11, 1)
                        rem(11 |-> 9) rem(13 |-> 9) remadd(9 |-> (3, 7))
                        rem(3 |-> 0) rem(7 |-> 4) .
    
    op init : Nat -> Vect .
    eq init(0) = |0> .
    eq init(NzN) = |0> (x) init(sd(NzN,1)) .

    op EPR : -> Vect .
    eq EPR = (0,1,0,-1) . (|0> (x) |0>) + (|1> (x) |1>) .

    vars V V1 V2 V' : Vect .
    vars M : Mat .
    vars BK1 BK2 : BraKet .

    --- building projectors
    op buildProj : Vect Nat Nat -> Mat .
    op buildProj : Vect Nat Nat Nat -> Mat .
    op buildProj* : Mat Nat Nat Nat -> Mat .
    eq buildProj(V, N1, N) = (I(N1) (x) (V x (V)^+) (x) MI(sd(N, N1 + 1))) .
    eq buildProj(V, N1, N2, N) = buildProj*(V x (V)^+, N1, N2, N) .
    eq buildProj*(BK1 (x) BK2 + M, N1, N2, N) = buildProj*(BK1 (x) BK2, N1, N2, N) + buildProj*(M, N1, N2, N) .
    eq buildProj*(BK1 (x) BK2, N1, N2, N) = I(N1) (x) BK1 (x) I(sd(N2, N1 + 1)) (x) BK2 (x) MI(sd(N, N2 + 1)) .
    
    --- checking the result with projectors
    op P : Vect Nat Nat Vect -> Bool .
    op P : Vect Nat Nat Nat Vect -> Bool .
    eq P(V, N1, N, V') = buildProj(V', N1, N) x V == V .
    ceq P(V, N1, N2, N, V') = (V1 == V)
    if M := buildProj(V', N1, N2, N)
    /\ V1 := M x V
    [print "M = " M "\nV1 = " V1] .
endfm

set print attribute on .
--- red EPR x (EPR)^+ .
--- red buildProj(EPR,1,3,14) .

red P(
    |0>(x)(
        |0>(x)|1>(x)|1>(x)|0>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1> + 
        |1>(x)|1>(x)|1>(x)|1>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>) + 
    |1>(x)(
        |0>(x)|1>(x)|1>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1> + 
        |1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>
    ),
    0, 5, 14, EPR
 ) .

eof
 (|0> x <0|)(x)I(x)I(x)I(x)I(x)(|0> x <0|)(x)MI(8) + 
 (|0> x <1|)(x)I(x)I(x)I(x)I(x)(|0> x <1|)(x)MI(8) + 
 (|1> x <0|)(x)I(x)I(x)I(x)I(x)(|1> x <0|)(x)MI(8) + 
 (|1> x <1|)(x)I(x)I(x)I(x)I(x)(|1> x <1|)(x)MI(8)

|0>(x)(
        |0>(x)|1>(x)|1>(x)|0>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1> + 
        |1>(x)|1>(x)|1>(x)|1>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>) + 

|0>(x)(
        |0>(x)|1>(x)|1>(x)|0>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1> + 
        |1>(x)|1>(x)|1>(x)|1>(x)|0>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>(x)|1>
    )

eof
red analyze([
    H(0) CX(0,1) H(2) CX(2,3)
    H(4) CX(4,5) H(6) CX(6,7)
    H(8) CX(8,9) H(10) CX(10,11)
    H(12) CX(12,13) network-coding,
    init(13)
]) .