in ../as4qc.maude

fmod RELAY-SCHEME is
    pr QC .
    ops a b : -> NzCpx .
    op |psi> : -> Vect .
    eq |psi> = (a . |0> + b . |1>) .
    eq a * a ^* + b * b ^* = (1,0,0,0) .
endfm

red analyze([
    H(1) CX(1,2) H(3) CX(3,4) CX(0,1) H(0)
    (P0(1) U (P1(1) X(2)))
    (P0(0) U (P1(0) Z(2)))
    CX(2,3) H(2)
    (P0(3) U (P1(3) X(4)))
    (P0(2) U (P1(2) Z(4))),
    |psi> (x) |0> (x) |0> (x) |0> (x) |0>
]) .