in ../as4qc.maude

fmod TELEPORT is
    pr QC .
    ops a b : -> NzCpx .
    op |psi> : -> Vect .
    eq |psi> = (a . |0> + b . |1>) .
    eq a * a ^* + b * b ^* = (1,0,0,0) .
    --- eq |psi> = a . |0> .
    --- eq a * a ^* = (1,0,0,0) .
    --- eq |psi> = b . |1> .
    --- eq b * b ^* = (1,0,0,0) .
endfm

red analyze([
    H(1) CX(1,2) CX(0, 1) H(0) 
    (P0(1) U (P1(1) X(2)))
    (P0(0) U (P1(0) Z(2))), 
    |psi> (x) |0> (x) |0>
]) .